# This is a basic workflow to help you get started with Actions

name: rcsoccersim3d_install

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_18:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: build foreign ver.
        run: |
          cd $GITHUB_WORKSPACE
          cmake .
          make -j$(nproc) rcsoccersim3d
          sudo make uninstall_all

          cmake . -DINSTALL_TO_SYSTEM=OFF -DWITH_ROBOVIZ=OFF
          make -j$(nproc)
          make rcsoccersim3d
          make uninstall_all
  
  build_18_domestic:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: build foreign ver.
        run: |
          cd $GITHUB_WORKSPACE
          cmake . -DDOMESTIC=ON
          make -j$(nproc) rcsoccersim3d
          sudo make uninstall_all

          cmake . -DDOMESTIC=ON -DINSTALL_TO_SYSTEM=OFF -DWITH_ROBOVIZ=OFF
          make -j$(nproc)
          make rcsoccersim3d
          make uninstall_all

  build_16:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: build foreign ver.
        run: |
          cd $GITHUB_WORKSPACE
          cmake .
          make -j$(nproc) rcsoccersim3d
          sudo make uninstall_all

          cmake . -DINSTALL_TO_SYSTEM=OFF -DWITH_ROBOVIZ=OFF
          make -j$(nproc)
          make rcsoccersim3d
          make uninstall_all
